# Generated by Django 3.2.23 on 2023-11-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitygoal', '0005_remove_sdg_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
